spring.application.name=astraflow-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://ep-square-silence-a8kg8rgi-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_1EHSo2qOTFtM
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

gemini.api.key=AIzaSyA1n7JerbVLKKTeXlhMg9EAZMyIMFDBwRM
gemini.api.model=gemini-2.0-flash-lite
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models?key=AIzaSyA1n7JerbVLKKTeXlhMg9EAZMyIMFDBwRM
